Update force-restart-runner.yml

diff --git a/.github/workflows/force-restart-runner.yml b/.github/workflows/force-restart-runner.yml
--- a/.github/workflows/force-restart-runner.yml
+++ b/.github/workflows/force-restart-runner.yml
@@ -1,58 +1,17 @@
-#
-# Copyright (C) 2024-2025 Antonino Scordino
-# Copyright (C) 2024-2025 Souhrud Reddy
-#
-# SPDX-License-Identifier: Apache-2.0
-#
-
-name: Start/Restart Selfhosted Runner
-on:
-  workflow_dispatch:
-
-jobs:
-  run-devspace-and-tmux:
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
-
-      # Install 'tmux'
-    - name: Set up environment
+      # Start 'runner' using 'run' instead of 'devspace' to bypass permission limits.
+    - name: Run crave runner
       run: |
-        sudo apt-get update
-        sudo apt-get install -y tmux
-
-      # Download and configure 'crave'.
-    - name: Configure the 'crave' environment
-      run: |
-        if [[ $DCDEVSPACE == *1* ]]; then
-        echo 'No need to set up crave, we are already running in devspace!'
-        else
-          mkdir ${HOME}/bin/
-          curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
-          mv ${PWD}/crave ${HOME}/bin/
-          sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
-          envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
-          rm -rf ${PWD}/crave.conf.sample          
-        fi
-      env:
-        CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
-        CRAVE_TOKEN: ${{  secrets.CRAVE_TOKEN  }}
-
-      # Start 'runner' in 'tmux'.
-    - name: Run crave devspace
-      run: |
-          crave ${{ secrets.CRAVE_FLAGS }} devspace -- "echo "Looking for runner..."
-          # Look for whether there's a runner folder set up
-          if [ -f actions-runner/run.sh ] ; then
-            echo "Runner found! Restarting it..."
+          crave ${{ secrets.CRAVE_FLAGS }} run --no-patch -- "
+          echo 'Checking for runner directory...'
+          if [ -d actions-runner ] ; then
+            echo 'Runner found! Starting it now...'
+            # Kill existing session if it exists and start a new one
+            tmux kill-session -t ghactions || true
+            tmux new-session -d -s ghactions './actions-runner/run.sh'
+            sleep 15
+            echo 'Runner started in background session: ghactions'
           else
-            echo "Error! Runner not found!"
+            echo 'Error! actions-runner directory not found!'
+            echo 'Please run the configure-runner workflow first.'
             exit 1
-          fi
-
-          tmux kill-session -t ghactions || true
-          tmux new-session -d -s ghactions 
-          tmux send-keys -t ghactions './actions-runner/run.sh' Enter 
-          echo "Runner Started""
+          fi"
